version: 0.2

env:
  variables:
    IMAGE_NAME: "simple-docker-service-120458a1f377"

phases:
  pre_build:
    commands:
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 723858002427.dkr.ecr.us-east-1.amazonaws.com"
  build:
    commands:
      - "docker build -t $IMAGE_NAME -f ./Dockerfile ."
      - "docker tag $IMAGE_NAME:latest 723858002427.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest"
  post_build:
    commands:
      - "if docker image inspect $IMAGE_NAME:latest > /dev/null 2>&1; then docker push 723858002427.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest; else echo 'Skipping push: image not built'; exit 1; fi"
